language: elixir
sudo: false
elixir: 1.8
notifications:
  recipients:
    - ben.wilson@cargosense.com
    - bruce.williams@cargosense.com
otp_release:
  - 21.1
script:
  - MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test
  - mix format --check-formatted
